# Permalinks
permalink:           pretty

# Setup
title:               Wenting Deng
tagline:             A Data Science Porject Blog
url:                 http://wentingd.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Wenting Deng
  url:               N/A
  email:             curelladeng@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/curelladeng

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
